name = "kitchen"
description = "a room where food is created using black magic"

[[contents]]
kind = "gateway"
name = "lounge"
target = "lounge"
obvious = true


[[contents]]
kind = "enemy"
name = "mold"
health = 10

[[contents]]
kind = "weapon"
name = "knife"
damage = 15

